Adds brief at_exit tutorial to README
Homebrew/homebrew-bundle pull request #1248
Opened 2023-09-17 01:36 UTC by colindean

This has come up at least thrice now in filed issues. I've also been using it without a problem in some Brewfiles, so let's document it.

My _sole_ hesitation here is the level of support for reaching into Homebrew and HB Bundle internals like this. I'd appreciate thoughts and guidance in that area.

A possible extension of this could be the extension of the Brewfile DSL to provide some convenience methods for common tasks, e.g.

```ruby
brew 'cowsay'

post_install do
  formula 'cowsay' do |f|
    system "#{f.bin}/cowsay 'All done!'"
  end
end
```

2023-09-17 03:09 UTC, jacobbednarz commented
👍 to this simple documentation example however, I don't really want to be encouraging folks to do things post install for specific formulas. to me, that really feels like it is outside our realm and should instead exist in the formula itself and if it doesn't belong there, folks can use the `at_exit` with their own logic.

2023-09-17 03:47 UTC, colindean commented
Oh yes, things in at_exit should not be things that would be better off in a formula post-install. Rather, it might be the installation of some pip packages after having installed python, or a user writing a standard configuration file if one doesn't exist for some tool.

2023-09-18 18:22 UTC, MikeMcQuaid requested changes
I appreciate the enthusiasm here but a few thoughts:
- this feels pretty heavy for the README. Perhaps better to have a dedicated "Tips and Tricks" page where we can just brain dump anything like this
- Really don't like digging into internals here. If we want to support doing things after a formula is installed: we should add a dedicated `after: "some_cmd"` (perhaps also with `before:`) so that hooks can be added in the existing DSL.

2023-09-18 18:57 UTC, colindean commented
Moving this out of the README makes sense. Would you prefer a top-level file or a docs directory? There are probably some other things suitable for docs, methinks. At the start of this section of the new tips doc, I can put something about "reaching into the internals might break" as a warning until we would do something more official.

2023-09-19 22:48 UTC, colindean commented
> Honestly I'd rather we just didn't document anything like that.

Are you OK with documenting what I've proposed here, then? They're internals but they're parts that are really unlikely ever to change.

2023-09-20 07:43 UTC, MikeMcQuaid commented
@colindean Would rather not, sorry; even if they aren't going to change, they are implementation details I don't want to encourage people to rely on.

2023-09-20 11:22 UTC, colindean commented
All right, I will close this then and we can document it when someone gets around to implementing it as a properly supported feature.

2023-09-20 11:22 UTC, closed without merging