[WIP] First pass at migrating logging puts to ohai/opoo, etc.
Homebrew/homebrew-bundle pull request #1249
Opened 2023-09-17 03:08 UTC by colindean

Work toward #1202, but untested. I did this commit in a codespace
that is flailing.

2023-09-18 18:29 UTC, MikeMcQuaid requested changes
As said in other issue: most of these changes don't make sense. `odebug` might do but all `ohai` and many `opoo` etc. use makes output worse, sorry.

2023-09-18 18:29 UTC, MikeMcQuaid commented on cmd/bundle.rb
> +      odebug "Kernel.exit" if args.debug?
```suggestion
      odebug "Kernel.exit"
```

may work as expected, worth a try.

2023-09-18 18:29 UTC, MikeMcQuaid commented on cmd/bundle.rb
> +      ofail "Interrupted"
Don't do this

2023-09-18 18:29 UTC, MikeMcQuaid commented on cmd/bundle.rb
> +      ofail e.backtrace if args.debug?
Don't want to do this, it makes the output worse for no real reason

2023-09-18 18:29 UTC, MikeMcQuaid commented on cmd/bundle.rb
> +      ohai(
Makes output worse

2023-10-10 03:51 UTC, colindean commented
I'll revisit this less hurriedly and haphazardly, and with actual testing, in the future. Devcontainers setup should make it easier to do meaningful drive-by contributions like this.

2023-10-10 03:51 UTC, closed without merging